name: Deploy to Spaceship

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Build application
        run: npm run build
        
      - name: Deploy to Spaceship
        uses: spaceship/action@v1
        with:
          api-key: ${{ secrets.SPACESHIP_API_KEY }}
          project-id: ${{ secrets.SPACESHIP_PROJECT_ID }}
          directory: ./out
          
      - name: Invalidate Cloudflare cache
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: cache purge --everything
